apiVersion: openchoreo.dev/v1alpha1
kind: Component
metadata:
  name: shipping
  namespace: default
spec:
  owner:
    projectName: microservices-demo

  componentType: deployment/service
  autoDeploy: true

  parameters:
    replicas: 1
    port: 50051
    resources:
      requests:
        cpu: "100m"
        memory: "64Mi"
      limits:
        cpu: "200m"
        memory: "128Mi"

---

apiVersion: openchoreo.dev/v1alpha1
kind: Workload
metadata:
  name: shipping
  namespace: default
spec:
  owner:
    componentName: shipping
    projectName: microservices-demo
  containers:
    main:
      image: shippingservice:v1
      env:
        - key: PORT
          value: "50051"
        - key: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "opentelemetry-collector.openchoreo-observability-plane:4317"
        - key: OTEL_SERVICE_NAME
          value: "shippingservice"
