apiVersion: openchoreo.dev/v1alpha1
kind: Component
metadata:
  name: currency
  namespace: default
spec:
  owner:
    projectName: microservices-demo

  componentType: deployment/service
  autoDeploy: true

  parameters:
    replicas: 1
    port: 7000
    resources:
      requests:
        cpu: "100m"
        memory: "64Mi"
      limits:
        cpu: "200m"
        memory: "128Mi"

---

apiVersion: openchoreo.dev/v1alpha1
kind: Workload
metadata:
  name: currency
  namespace: default
spec:
  owner:
    componentName: currency
    projectName: microservices-demo
  containers:
    main:
      image: currencyservice:latest
      env:
        - key: PORT
          value: "7000"
        - key: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "grpc://opentelemetry-collector.openchoreo-observability-plane:4317"
        - key: OTEL_SERVICE_NAME
          value: "currencyservice"
