apiVersion: openchoreo.dev/v1alpha1
kind: Component
metadata:
  name: frontend
  namespace: default
spec:
  owner:
    projectName: microservices-demo

  componentType: deployment/web-application
  autoDeploy: true

  parameters:
    replicas: 1
    port: 8080
    resources:
      requests:
        cpu: "100m"
        memory: "64Mi"
      limits:
        cpu: "200m"
        memory: "128Mi"

---

apiVersion: openchoreo.dev/v1alpha1
kind: Workload
metadata:
  name: frontend
  namespace: default
spec:
  owner:
    componentName: frontend
    projectName: microservices-demo
  containers:
    main:
      image: frontend:latest
      env:
        - key: PORT
          value: "8080"
        - key: PRODUCT_CATALOG_SERVICE_ADDR
          value: "productcatalog:80"
        - key: CURRENCY_SERVICE_ADDR
          value: "currency:80"
        - key: CART_SERVICE_ADDR
          value: "cart:80"
        - key: RECOMMENDATION_SERVICE_ADDR
          value: "recommendation:80"
        - key: SHIPPING_SERVICE_ADDR
          value: "shipping:80"
        - key: CHECKOUT_SERVICE_ADDR
          value: "checkout:80"
        - key: AD_SERVICE_ADDR
          value: "ad:80"
        - key: SHOPPING_ASSISTANT_SERVICE_ADDR
          value: "-"
        - key: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "opentelemetry-collector.openchoreo-observability-plane:4317"
        - key: OTEL_SERVICE_NAME
          value: "frontend"
