apiVersion: openchoreo.dev/v1alpha1
kind: Component
metadata:
  name: recommendation
  namespace: default
spec:
  owner:
    projectName: microservices-demo

  componentType: deployment/service
  autoDeploy: true

  parameters:
    replicas: 1
    port: 8080
    resources:
      requests:
        cpu: "100m"
        memory: "220Mi"
      limits:
        cpu: "200m"
        memory: "450Mi"

---

apiVersion: openchoreo.dev/v1alpha1
kind: Workload
metadata:
  name: recommendation
  namespace: default
spec:
  owner:
    componentName: recommendation
    projectName: microservices-demo
  containers:
    main:
      image: recommendationservice:latest
      env:
        - key: PORT
          value: "8080"
        - key: PRODUCT_CATALOG_SERVICE_ADDR
          value: "productcatalog:80"
        - key: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "opentelemetry-collector.openchoreo-observability-plane:4317"
        - key: OTEL_SERVICE_NAME
          value: "recommendationservice"
